// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DfHeader: typeof import('./components/organism/DfHeader.vue')['default']
    DfInputText: typeof import('./components/atoms/input/DfInputText.vue')['default']
  }
}

export { }
